name: deploy-app

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Deploy to AWS EC2
        run: |
          ssh -i ${{ secrets.AWS_PRIVATE_KEY }} ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOSTNAME }} "cd /home/ubuntu/app && git pull origin main && sudo systemctl restart app"
